---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzjoperator
  namespace: controller
  labels:
    app: hzjoperator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hzjoperator
  template:
    metadata:
      labels:
        app: hzjoperator
    spec:
      serviceAccountName: sa-custom-controller
      containers:
      - name: hzjoperator
        image: hzjoperator:v2
